---
minio_servers:
  hosts:
    minio1:
      ansible_host: 83.233.237.136
      ansible_port: 622
      ansible_user: owntube_ansible
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    minio2:
      ansible_host: 83.233.237.136
      ansible_port: 623
      ansible_user: owntube_ansible
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    minio3:
      ansible_host: 82.183.39.110
      ansible_port: 622
      ansible_user: owntube_ansible
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
...
