---
minio_servers:
  hosts:
    minio1:
      ansible_host: 83.233.237.207
      ansible_port: 622
      ansible_user: owntube_ansible
    minio2:
      ansible_host: 83.233.237.209
      ansible_port: 622
      ansible_user: owntube_ansible
    minio3:
      ansible_host: 82.183.39.110
      ansible_port: 622
      ansible_user: owntube_ansible
