---

minio_microk8s_servers:
  hosts:
    # a12a.mabl.online
    node-1:
      ansible_host: 83.233.237.206
      ansible_port: 622
      ansible_user: owntube_ansible
    # a12b.mabl.online
    node-2:
      ansible_host: 83.233.237.208
      ansible_port: 622
      ansible_user: owntube_ansible
    # v1517a.mabl.online
    node-3:
      ansible_host: 82.183.39.110
      ansible_port: 622
      ansible_user: owntube_ansible
    # v1517b.mabl.online
    node-4:
      ansible_host: 82.183.39.110
      ansible_port: 624
      ansible_user: owntube_ansible

...
