---
minio_servers:
  hosts:
    # a12a.mabl.online
    minio1:
      ansible_host: 83.233.237.206
      ansible_port: 622
      ansible_user: owntube_ansible
    # a12b.mabl.online
    minio2:
      ansible_host: 83.233.237.208
      ansible_port: 622
      ansible_user: owntube_ansible
    # v1517a.mabl.online
    minio3:
      ansible_host: 82.183.39.110
      ansible_port: 622
      ansible_user: owntube_ansible
    # v1517b.mabl.online
    minio4:
      ansible_host: 83.233.237.208
      ansible_port: 623
      ansible_user: owntube_ansible
