name: Continuous Deployment with Ansible

on:
  push:
    branches: ["main"]

jobs:
  run-ansible-playbook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run bootstrap.yml playbook
        uses: dawidd6/action-ansible-playbook@v2.8.0
        with:
          playbook: bootstrap.yml
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: |
            [83.233.237.136]:622 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE4vBfnFG/U76eqgbLFqkp2yMKR3cpNrwPc6lTZAFNfq
            [82.183.39.110]:622 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINyaOsHcT6Sy2UJMg40vxq+xxhPvvaSVjS2u0pxKy1dT
            [83.233.237.136]:623 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKSP+L5mjXBT5UqCi9/rHWFAeMCqhGyxYVbSQfmDkNuB
          vault_password: ${{ secrets.VAULT_PASSWORD }}
          options: |
            --diff
